[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cmake>=3.18",
    "scikit_build @ git+https://github.com/YannickJadoul/scikit-build@vs2019",
]
build-backend = "setuptools.build_meta"
