[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cmake>=3.18",
    "scikit-build>=0.13",
]
build-backend = "setuptools.build_meta"

[tool.check-manifest]
ignore = [
    ".clang-format",
    ".readthedocs.yml",
    "binder",
    "binder/*"
]
