name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  basic:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
        python: [2.7, 3.5, 3.6, 3.7, 3.8]

    name: Basic
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: 'x64'

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.3

      - name: Install requirements
        run: |
          pip install --user --upgrade pip setuptools wheel
          pip install --user --upgrade -r tests/requirements.txt

      - name: Configure
        run: cmake -S . -B build

      - name: Compile
        run: cmake --build build -j 2

      - name: Run tests
        run: cmake --build build --target tests
