name: Wheels

on:
  push:
    branches:
      - master
      - stable
      - docs*
      - actions*
  workflow_dispatch:

jobs:
  wheels:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]

    name: Wheels • ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install requirements
        run: |
          python -m pip install cibuildwheel twine

      - name: Configure cibuildwheel
        run: |
          echo "::set-env name=CIBW_SKIP::pp*-*"

      - name: Configure cibuildwheel for manylinux
        run: |
          echo "::set-env name=CIBW_BEFORE_ALL::PY37_BIN=/opt/python/cp37-cp37m/bin && \$PY37_BIN/pip install cmake && ln -s \$PY37_BIN/cmake /usr/local/bin/cmake"
          echo "::set-env name=CIBW_ENVIRONMENT::PIP_ONLY_BINARY='numpy'"
        if: runner.os == 'Linux'

      - name: Run cibuildwheel
        run: |
          cibuildwheel

      - name: Check built wheels
        run: |
          twine check wheelhouse/*

      - name: Upload built wheels
        uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl
